# Generated by Django 6.0.2 on 2026-02-25 20:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MinecraftServer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('server_name', models.CharField(max_length=100, unique=True)),
                ('mc_version', models.CharField(default='LATEST', max_length=20)),
                ('difficulty', models.CharField(default='normal', max_length=20)),
                ('max_players', models.IntegerField(default=20)),
                ('allow_tlauncher', models.BooleanField(default=False)),
                ('port_number', models.IntegerField(blank=True, null=True, unique=True)),
                ('container_id', models.CharField(blank=True, max_length=100, null=True)),
                ('is_running', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
