# Generated by Django 6.0.2 on 2026-02-26 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='minecraftserver',
            name='server_password',
            field=models.CharField(default='defaultpass', max_length=128),
            preserve_default=False,
        ),
    ]
