# Generated by Django 6.0.2 on 2026-02-28 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_minecraftserver_server_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='minecraftserver',
            name='seed',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
