# Generated by Django 6.0.2 on 2026-03-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0006_minecraftserver_ram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minecraftserver',
            name='ram',
            field=models.IntegerField(choices=[(2, '2GB - Small (1-4 Players) ~0.02$/hour'), (4, '4GB - Medium (4-10 Players) ~0.04$/hour'), (8, '8GB - Large (10-20 Players) ~0.08$/hour'), (16, '16GB - Extra Large (Modded or for upto 40 Players) ~0.17$/hour')], default=4),
        ),
    ]
